export const QUERY_KEYS = {
  products:          (filters = {}) => ['products', filters],
  product:           (id)           => ['products', id],
  outfitSuggestions: (productId)    => ['outfitSuggestions', productId],
  cart:              ()             => ['cart'],
  myOrders:          (params = {})  => ['myOrders', params],
  myOrder:           (id)           => ['myOrders', id],
  chatMessages:      (sessionId)    => ['chatMessages', sessionId],
  ghnProvinces:      ()             => ['ghn', 'provinces'],
  ghnDistricts:      (provinceId)   => ['ghn', 'districts', provinceId],
  ghnWards:          (districtId)   => ['ghn', 'wards', districtId],
  shippingFee:       (params)       => ['shippingFee', params],
  staffOrders:       (params = {})  => ['staff', 'orders', params],
  staffOrder:        (id)           => ['staff', 'orders', id],
  returns:           (params = {})  => ['staff', 'returns', params],
  return:            (id)           => ['staff', 'returns', id],
  stats:             (period)       => ['admin', 'stats', period],
  adminProducts:     (params = {})  => ['admin', 'products', params],
  users:             (params = {})  => ['admin', 'users', params],
};
